# Generated by Django 5.1.15 on 2026-07-05 16:15

import django.db.models.deletion
import shorts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('video', models.FileField(storage=shorts.models.ProtectedShortStorage(), upload_to=shorts.models.short_video_path)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers only'), ('private', 'Private (only me)')], default='public', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shorts.short')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['visibility', '-created_at'], name='shorts_shor_visibil_f6534c_idx'),
        ),
        migrations.AddConstraint(
            model_name='shortlike',
            constraint=models.UniqueConstraint(fields=('user', 'short'), name='uniq_short_like'),
        ),
    ]
