# Generated by Django 5.1.15 on 2026-07-06 13:15

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=chat.models.ProtectedDMStorage(), upload_to=chat.models.dm_attachment_path),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File')], max_length=8),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
