# Generated by Django 5.1.15 on 2026-07-06 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('arcade', 'Arcade'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('racing', 'Racing'), ('horror', 'Horror'), ('casual', 'Casual'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['genre', 'status'], name='games_game_genre_0e4551_idx'),
        ),
    ]
